module.exports = {
	STATUS_CODE: {
		OK: 200,
		TRIPLEA: 151,
		CREATED: 201,
		ACCEPTED: 202,
		NO_CONTENT: 204,
		INFO: 250,
		NON_AUTHORITATIVE: 203,
		BAD_REQUEST: 400,
		UN_AUTHORIZED: 401,
		FORBIDDEN: 403,
		RESOURCE_NOT_FOUND: 404,
		PROXY_AUTH_FAILED: 412,
		TOO_MANY_REQUESTS: 429,
		VALIDATION_FAILURE: 450,
		INTERNAL_SERVER_ERROR: 500,
		SERVICE_UNAVAILABLE: 503,
		SERVER_TIMEOUT: 504,
	},
	ERROR_MSGS: {
		INTERNAL_SERVER_ERROR: "Unable to process,Please Try Again",
		ACCOUNT_EXISTS: "Account already exists. Please login",
		ACCOUNT_DISABLED:
			"Your account has been disabled, please reach out to our support",
		ACCOUNT_NOT_FOUND: "Account not found",
		ACCOUNT_BLOCKED:
			"Your account has been blocked, please reach out to our support",
		ACCOUNT_LOCKED:
			"Your account has been blocked, please use forgot password option to reset password and login.",
		ACCOUNT_LOCKED_EMAIL_TRIGGERED:
			"Your account has been blocked, mail has been triggered to reset password.",
		IP_LOCKED: "Please try again later.",
		INVALID_LOGIN: "Invalid email or/and password.",
		USER_NOT_FOUND: "User not found",
		WALLET_NOT_FOUND: "Account not found, related to the given wallet.",
		LOGIN_WITH_EMAIL: "Please login with Email and password",
		INCORRECT_PASSWORD: "current Password Incorrect",
		LOGIN_WITH_GOOGLE: "Please login with Google",
		FORGOT_PASSWORD_TOKEN_EXPIRED: "Token has expired.",
		TOKEN_MISSING: "No token provided",
		TOKEN_SESSION_EXPIRED: "Token Session Expired",
		INVALID_TOKEN_FORMAT: "Token invalid format",
		INVALID_TOKEN_TYPE: "Invalid Token type",
		INVALID_CODE: "Invalid Code",
		INVALID_TOKEN_ID: "Invalid Token Id",
		GOOGLE_AUTHENTICATION_FAILED:
			"Google authentication failed. Please try again.",
		LINKEDIN_AUTHENTICATION_FAILED:
			"Linkedin authentication failed. Please try again.",
		NOT_HAVE_A_SUFFICIENT_WALLET_AMOUNT: "Not Have A Sufficent Wallet Amount",
	},
	INFO_MSGS: {
		ITEMS_NOT_AVAILABLE: "No data found",
		NO_DATA: "No data found",
		CREATED_SUCCESSFULLY: "Created successfully",
		UPDATED_SUCCESSFULLY: "Updated successfully",
		SUCCESS: "Request Success",
		SUCCESSFUL_REGISTER:
			"Your registration with Brant Ford India is successful.",
		SUCCESSFUL_UPDATE: "Successfully updated",
		WELCOME_MSG: "Welcome to Client API Services_v4.",
		SUCCESSFUL_LOGIN: "Successfully logged in.",
		SUCCESSFUL_ENABLE: "2FA enabling requested successfully.",
		SUCCESSFUL_RESET: "2FA is successfully reset on your request.",
		PASSWORD_CHANGED: "Your password has been changed successfully.",
		VERIFICATION_EMAIL: "Verification Email send successfully.",
		EMAIL_NOT_VERIFIED: "Email not verified, Please verify it.",
		EMAIL_VERIFIED: "Email already Verified. Please login",
		EMAIL_SEND: "Email sent to the registered account.",
		ACCOUNT_VERIFIED: "Your account has been verified, Please login.",
		TWO_FACTOR_SUCCESS: "Successfully configured 2FA",
		TWO_FACTOR_ENABLED: "2FA enabled successfully",
		TWO_FACTOR_DISABLED: "2FA disabled successfully",
		SUCCESSFUL_LOGOUT: "Successfully logged out.",
		USERNAME_AVAILABLE: "Username available",
		USERNAME_NOT_AVAILABLE: "Username not available",
		TRAN_NOT_AVAILABLE: "Wallet Transaction Not Available",
		ALREADY_VIEWED: "You have already viewed the Building",
		ALREADY_VIEWED_REGISTRY: "You have already viewed the Registry",
		VIEW_ADDED: "Successfully updated view",
		ALREADY_TRACK: "You have already track the Building",
		REMOVE_TRACK: "You have remove track the Building",
		TRACK_ADDED: "Successfully updated track",
		READ_SUCCESSFULLY: "Read",
		NOTIFICATION_NOT_FOUND: "helpers/constant.js Not Found",
		MSG_REQUIRED: "is required",
		DEBIT_SUCCESS: "Wallet debited successfully",
	},
};
